name: meson_test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install libwayland-dev libglew-dev libsdl2-dev libopenvr-dev libudev-dev libinput-dev libxkbcommon-dev
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - run: pip install meson ninja

      - run: meson build
        working-directory: ./main
        env:
          CC: gcc

      - run: ninja -C build test
        working-directory: ./main

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Test_Log
          path: main/build/meson-logs/testlog.txt
